newPRWelcomeComment: |
  Thank you for making your first PR on `data`!

  We are glad about every contribution!

firstPRMergeComment: |
  Congrats on your first merge! Thank you for helping us to keep the database up to date.
