newPRWelcomeComment: |
  Thank you for making your first PR on `data`!

  We are glad about every contribution!

firstPRMergeComment: |
  Congrats on your first merge! Thank you for helping us keep this repository updated.

  Did you know we are currently running a [Hacktoberfest event](https://www.datarequests.org/blog/hacktoberfest-2021/)? Register through our website to get some swag for your contribution.
